/*

The purpose of this module is so the PC either branches or
+4s depending on a cntrl sig
this will be done via a mux. 

by convention

pc_src = 0 → take the normal sequential PC (pc_plus4)

pc_src = 1 → take the branch/jump target

note to the reader, pc_src is a control signal generated by my control unit.
Again:
If the instruction is not a branch or jump → control unit sets pc_src = 0

If the instruction is a branch or jump → control unit sets pc_src = 1

but note that I do not define pc_src in this module, it will come later
from my decoder/control logic—a thing that will look at instructions and ALU comparison flags.


As I am coding this for anyone to learn from it, lets understand some of the choices 
I am making.

My ROM holds a 32 bit instruction, and can increment the PC by 4. So let me ask you,
if pc_curr = 32'h0000_1000 which ROM index is used to fetch the instruction?

To answer this,

We need to talk more about our system.

Starting with ROM, we know it is word addressed—meaning you do not index by bytes, rather 32 bit words. 

This impresses a very unintuitive question on us, how does the PC, which is byte aligned,
address the memory with a different alignment? This is unintuitive since the obvious answer is wrong.


Since this is a key concept, I will explore it a bit.

Recall, the PC is a byte address, meaning the smallest unit of bits you 
can address is 8.

Though the instruction memory, IMEM, is a list (aka array) of 32 bit words, not bytes.
In other words, each instruction is four bytes.

what this means is that our memory looks like


rom[0] → bytes 0x…0000 to 0x…0003
rom[1] → bytes 0x…0004 to 0x…0007
rom[2] → bytes 0x…0008 to 0x…000B
...

Great, (recapping) you now understand that IMEM consists of 4 bytes—32-bit word of data—and PC is a 32 bit register holding a byte address.
But you should ask, both technically are 32 bit words, so what are we saying about one being 4 bytes and the other being 1 byte.
Why are we even talking about bytes? what if I want to increment by 1 bit?

These are all design choices, namely so things work smoothly. Each IMEM instruction is 32 bits long since that is how much information our system needs.
We build the PC around this constraint, ask another question, how? Well we won't work in bits since those are too meaningless on their own.
But we also won't work in anything larger than bytes—they are atomic, and this is one of the ways 
we see atomicity. So, we will take PC, a 32 bit register, and make its numerical value
represent a byte address; since 32/8 = 4, PC+1 where both are in bytes, allows
us to access each unit, byte, aka smallest meaningful piece of information in an IMEM address—
but this is never done, YOU DO NOT WANT TO BE IN THE MIDDLE OF AN INSTRUCTION, that causes all sorts of errors.

So, now you know that PC will be byte addressable since it is the best choice, and 32 bit IMEM instructions is simply a choice for the system.

Ergo, if we have a PC address, some 32 bit word, what it represents is a count of bytes—not anything else.
You may hear that it is "what instruction you're at," but know that we are programming it, not quite, it is simply a count.

It might make sense that we need to count up four times as 32/8 =4 in order to travel a full word in IMEM,

but the unintuitive part is that in address the array ROM is, the input is not whatever PC is. As a matter of fact, the input parameters—
which is a hardware port of say 10—may not accept a 32 bit word. 

before dealing with that, let's tackle a similar related problem that may also be in your mind.
IMEM is word addressed—ROM is also word addressed in this design. They don't understand each other. The solution is simple, think back to the basics of division:
If every 4 bytes is one word, we need groups of four, and if we are now to count those groups of 4, 
each count is exactly one instruction since it contains 4 bytes


Ergo to convert to a word index, take PC/4, now it is no longer a count of bytes but of words.

There is a second more common line of thought that I did not come up with to explain this choice.
the Imem_index is 4 bytes long, and the PC counts bytes, that is it should move in multiples of 4.

Personally, I do not find any reason other than this satisfactory, and the internet 
has been unhelpful at explaining it—though I should say that you could understand
it without what I am going to say, but here is how you could have seen it for yourself.

Think about the position notation: (a_n-1...a1a0)2 = d2^n-1 + ... + b2 + c where all coeffs are either 0 or 1.
You should know that we need to stay aligned, as in multiple of 4, so if we divide by 4, we simply factor 2^2 out of 
each term and remove it. The only ones that cannot do this are the last two, those with b and c as coeffs. Ergo, 
division by four is really a bit shift right, making us remove those bottom two bits, which at most add up to 3—
no word will ever end in 1,2,3. Only 0, so doing this forces it to be zero, while at the same time 
making us count the bytes properly.

*WARNING. To be clear, “No word will ever end in 1,2,3. Only 0” is NOT A STATEMENT YOU SHOULD GENERALIZE.
It is only true for instruction memory, Instruction fetch is constrained; data memory is not.

The key, word_index = PC[31:2] = PC / 4

but note this is a design choice.

Now as for the index of however ROM counts, that is entirely up to you, depending on how you design your system.
*/




*/


module pc_mux(
    input  logic [31:0] pc_plus4,
    input  logic [31:0] branch_target,
    input  logic        pc_src,
    output logic [31:0] pc_next
);

    assign pc_next = pc_src ? branch_target : pc_plus4;

endmodule


/*

A mux in hardware is just a conditional selection between two (or more) signals.
In RTL, the cleanest, synthesizable way to express that is the code above...

*/
